### ISSUE TITLE
Gotify integration broken since release v2.3-ls139

### ISSUE THREAD

**Issue by pjbroad** [linuxserver/docker-healthchecks#97] opened 2022-10-22 16:08 UTC
## Expected Behavior
I've been using the Gotify integration for a while.  You can test and integration using the integration tab of a project.  This succeeds with versions prior to v2.3-ls139,

## Current Behavior
With version v2.3-ls139 and v2.3-ls140, the Gotify integration always fails. For my test project, I get the message "Could not send a test notification. Connection failed."  There is nothing of note in the logs, not even with Debug enabled.

## Steps to Reproduce
1. Setup a Gotify integration for a project.
2. Use the "test" button on the integration tab.

## Environment
OS: Ubuntu 22.04 LTS
CPU architecture: x86_64
How docker service was installed: OS repo via apt

## Command used to create docker container (run/create/compose/screenshot)
----> section from docker-compose.yml
    image: lscr.io/linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=${STNDUSERID}
      - PGID=${STNDGROUPID}
      - SITE_ROOT=https://healthchecks.${LOCALDOMAIN}:${LOCALPORT}
      - SITE_NAME=Home Healthchecks
      - DEFAULT_FROM_EMAIL=hc@${HOMEDOMAIN}
      - SUPERUSER_EMAIL=${HEALTHCHECKSSUEMAIL}
      - SUPERUSER_PASSWORD=${HEALTHCHECKSSUPASS}
      - REGENERATE_SETTINGS=True
      - DEBUG=True
    volumes:
      - ./healthchecks/config:/config
    restart: unless-stopped

## Docker logs
[pid: 175|app: 0|req: 2/45] 172.22.0.8 () {58 vars in 1239 bytes} [Sat Oct 22 15:55:24 2022] POST /integrations/0e2f3764-d07b-4b69-bddf-a94d6549cedd/test/ => generated 0 bytes in 497 msecs (HTTP/1.0 302) 10 headers in 554 bytes (1 switches on core 0)
[pid: 175|app: 0|req: 3/46] 172.22.0.8 () {52 vars in 1289 bytes} [Sat Oct 22 15:55:25 2022] GET /projects/8a287f56-2ca5-4f30-a8bb-e53a9bfdab60/integrations/ => generated 24915 bytes in 53 msecs (HTTP/1.0 200) 10 headers in 499 bytes (1 switches on core 0)

## Other Comments
I'd be very happy to debug if you have something I could do to help.

**Comment by pjbroad** [comment] 2022-10-22 16:23
I should add that sending a message to my Gotify instance from within the healthcheck container, works:
`curl -X POST "https://<my gotify domain>/message?token=<token>" -F "title=my title" -F "message=my message"`

**Comment by NiNiyas** [comment] 2022-10-31 06:41
Also running into the same issue when using webhooks. Downgrading to [v2.3-ls138](https://github.com/linuxserver/docker-healthchecks/releases/tag/v2.3-ls138) works.

**Comment by thespad** [comment] 2022-10-31 07:48
Could be the change from requests to pycurl in 2.4.0, I'll do some tests

**Comment by thespad** [comment] 2022-10-31 17:00
I can reliably replicate the problem, but the logging is rubbish and using pycurl directly inside the container to interface with my local gotify server seems to work fine, so I've not really got any idea how to go about troubleshooting this.

**Comment by nigelm** [comment] 2022-12-22 11:47
Same issue with pushover notification and ntfy (only available in very recent versions).
Still showing in v2.5-ls146

No useful log data :-(

**Comment by thespad** [comment] 2022-12-22 12:19
Can you try doing an `apk add py3-curl` inside the container and see if it makes any difference? I'm wondering if there's a dependency missing somewhere that pip isn't installing.

**Comment by nigelm** [comment] 2022-12-22 14:21
Tried that - no difference to running system...

However that could be as the processes are running (everything already loaded), and its tricky to restart them in the container without the container closing down...

Looking in the container - fresh start - the path `/usr/lib/python3.10/site-packages/curl/__init__.py` which should be the pycurl code, does exist and looks like the content on github

**Comment by thespad** [comment] 2022-12-22 16:54
Can you try `lspipepr/healthchecks:v2.5-pkg-1eaf64f2-pr-101` and see if it helps.

**Comment by nigelm** [comment] 2022-12-23 08:30
> Can you try this PR image: `lspipepr/healthchecks:v2.5-pkg-1eaf64f2-pr-101` and see if it helps.

That image behaves the same as mainline 2.5 image - an attempt to test the pushover integration gives a banner with

    Could not send a test notification. Connection failed.

**Comment by nigelm** [comment] 2022-12-23 08:54
Just as a check I have tested using a fresh test config (exactly as per the sample other than adding the Pushover config) using the official `healthchecks/healthchecks` image latest version.

This does successfully send a pushover notification.

**Comment by nigelm** [comment] 2022-12-23 09:21
And I have a culprit...

As of version 2.4 healthchecks blocks all connections to private IP ranges **including if you are using a http proxy in private IP address space** unless `INTEGRATIONS_ALLOW_PRIVATE_IPS` is set true.

See
- https://github.com/healthchecks/healthchecks/issues/725
- https://github.com/healthchecks/healthchecks/issues/654
- https://healthchecks.io/docs/self_hosted_configuration/#INTEGRATIONS_ALLOW_PRIVATE_IPS

I added 
```
INTEGRATIONS_ALLOW_PRIVATE_IPS = True
```
to `config/local_settings.py` (likely could have gone in `docker-compose.yaml` but hadn't checked how much this image picks up off the environment).

Our installation, like many corporate docker installs does not have open access to internet address space so setting up proxy settings is routine, and I had overlooked this as it used to just work.

**Comment by thespad** [comment] 2022-12-23 09:30
That's such a weird random thing to start blocking by default without calling it out in the release notes anywhere.

I'll get the PR and readme docs updated to account for it.

**Comment by thespad** [comment] 2022-12-23 10:07
@nigelm OK can you test with `lspipepr/healthchecks:v2.5-pkg-e78fe047-pr-101`, it should now support setting `INTEGRATIONS_ALLOW_PRIVATE_IPS` as an environment variable that should be honoured (I've also updated the readme to call it out, given the issues it can cause if not set).

**Comment by nigelm** [comment] 2022-12-23 10:34
Can @pjbroad and @NiNiyas check whether `INTEGRATIONS_ALLOW_PRIVATE_IPS = True`  fixes things for them.  It seems unlikely that I have usurped their issue for something completely different but worth checking.

**Comment by nigelm** [comment] 2022-12-23 10:40
> @nigelm OK can you test with `lspipepr/healthchecks:v2.5-pkg-e78fe047-pr-101`, it should now support setting `INTEGRATIONS_ALLOW_PRIVATE_IPS` as an environment variable that should be honoured (I've also updated the readme to call it out, given the issues it can cause if not set).

Tested with modifications to `local_settings.py` commented out, and `INTEGRATIONS_ALLOW_PRIVATE_IPS=True` set in the docker-compose environment section.

Test notification via Pushover worked.

**Comment by NiNiyas** [comment] 2022-12-23 10:55
> Can @pjbroad and @NiNiyas check whether `INTEGRATIONS_ALLOW_PRIVATE_IPS = True` fixes things for them using `lspipepr/healthchecks:v2.5-pkg-e78fe047-pr-101`. It seems unlikely that I have usurped their issue for something completely different but worth checking.

I can confirm that this fixes webhooks. Tested on latest tag right now.

**Comment by pjbroad** [comment] 2022-12-23 15:34
I can also confirm that adding "INTEGRATIONS_ALLOW_PRIVATE_IPS = True" to config/local_settings.py for the latest version fixes the reported issue. Great work @nigelm, thank you.

**Comment by thespad** [comment] 2022-12-23 16:18
Thanks for testing guys. PR merged and should be built within the hour.

**Closed** 2022-12-23 16:18 UTC
